/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.example.generatedClasses;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FILTRER = 1;
  /** RegularExpression Id. */
  int CHOISIR = 2;
  /** RegularExpression Id. */
  int CALCULER = 3;
  /** RegularExpression Id. */
  int GROUPER = 4;
  /** RegularExpression Id. */
  int MOYENNE = 5;
  /** RegularExpression Id. */
  int CHARGER = 6;
  /** RegularExpression Id. */
  int AFFICHER = 7;
  /** RegularExpression Id. */
  int PAR = 8;
  /** RegularExpression Id. */
  int MAX = 9;
  /** RegularExpression Id. */
  int MIN = 10;
  /** RegularExpression Id. */
  int SOMME = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int WHITESPACE = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int NEQ = 17;
  /** RegularExpression Id. */
  int GT = 18;
  /** RegularExpression Id. */
  int LT = 19;
  /** RegularExpression Id. */
  int GTE = 20;
  /** RegularExpression Id. */
  int LTE = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int LPAREN = 23;
  /** RegularExpression Id. */
  int RPAREN = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"FILTRER\"",
    "\"CHOISIR\"",
    "\"CALCULER\"",
    "\"GROUPER\"",
    "\"MOYENNE\"",
    "\"CHARGER\"",
    "\"AFFICHER\"",
    "\"PAR\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"SOMME\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<STRING>",
    "<WHITESPACE>",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
  };

}
